-- Create collections table
CREATE TABLE IF NOT EXISTS collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  display_order INTEGER DEFAULT 0
);

-- Create junction table for products <-> collections
CREATE TABLE IF NOT EXISTS product_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  collection_id BIGINT REFERENCES collections(id) ON DELETE CASCADE,
  display_order INTEGER DEFAULT 0,
  UNIQUE(product_id, collection_id)
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_collections_slug ON collections(slug);
CREATE INDEX IF NOT EXISTS idx_product_collections_product_id ON product_collections(product_id);
CREATE INDEX IF NOT EXISTS idx_product_collections_collection_id ON product_collections(collection_id);

-- Enable RLS
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_collections ENABLE ROW LEVEL SECURITY;

-- Policies (Public Read, Admin Write)
CREATE POLICY "Public can read collections" ON collections
  FOR SELECT USING (true);

CREATE POLICY "Public can read product_collections" ON product_collections
  FOR SELECT USING (true);

-- Insert default collections
INSERT INTO collections (name, slug, description, display_order)
VALUES 
  ('Best Sellers', 'best-sellers', 'Top rated products loved by our customers', 1),
  ('New Arrivals', 'new-arrivals', 'The latest trends just in', 2),
  ('Featured', 'featured', 'Hand-picked items for you', 3)
ON CONFLICT (slug) DO NOTHING;
